### ISSUE TITLE
Debugging scripts fails with the gemlogger: Permission denied: '/tmp/gempython.log'

### ISSUE THREAD

**Issue by BenjaminRS** [cms-gem-daq-project/cmsgemos#259]
## Brief summary of issue

As part of attempting to implement [vfatqc-python-scripts#224](https://github.com/cms-gem-daq-project/vfatqc-python-scripts/issues/224) I am testing some new code. The code failed but instead of getting useful feedback I received a message stating the gemlogger having permission errors.

### Types of issue

- [x] Bug report (report an issue with the code)
- [ ] Feature request (request for change which adds functionality)

## Expected Behavior

Expected tho see the debugging output on where python is failing.

## Current Behavior

Instead I currently get his back:
> Traceback (most recent call last):
>   File "/afs/cern.ch/user/b/benjamin/GEMDev/TestConn/venv/cc7/py2.7/lib/python2.7/site-packages/gempython/scripts/testConnectivity.py", line 868, in <module>
>     gemlogger = getGEMLogger(__name__)
>   File "/afs/cern.ch/user/b/benjamin/GEMDev/TestConn/venv/cc7/py2.7/lib/python2.7/site-packages/gempython/utils/gemlogger.py", line 180, in getGEMLogger
>     logging.config.fileConfig(logcfg, disable_existing_loggers=False)
>   File "/usr/lib64/python2.7/logging/config.py", line 78, in fileConfig
>     handlers = _install_handlers(cp, formatters)
>   File "/usr/lib64/python2.7/logging/config.py", line 156, in _install_handlers
>     h = klass(*args)
>   File "/usr/lib64/python2.7/logging/__init__.py", line 902, in __init__
>     StreamHandler.__init__(self, self._open())
>   File "/usr/lib64/python2.7/logging/__init__.py", line 925, in _open
>     stream = open(self.baseFilename, self.mode)
> IOError: [Errno 13] Permission denied: '/tmp/gempython.log'

### Steps to Reproduce (for bugs)

Edit code in cmsgemos/gempython which will fail due to an issue in python. 

## Possible Solution (for bugs)

(Brian:) Modify utils/gemlogging_config.cfg and change `args=("/tmp/gempython.log", 'a')` to `args=("/tmp/username/gempython.log", 'a')`.
A longer term solution would be if this somehow used $USER of the active user.

## Your Environment

* Version used: branch generic-amc-RPC-v3-short-term
* Shell used: bash

**Comment by BenjaminRS** [comment]
@jsturdy @bdorney was suggesting that this could use the $USER variable as a solution

**Comment by BenjaminRS** [comment]
testing in python on gem904qc8daq I tried:
`import os`
`os.getlogin()`
this produced:
> 'benjamin'

So that could be the answer? Maybe if a couple other try it, and if it also gives the correct username I can make a PR with it?

**Comment by jsturdy** [comment]
My only constraint here would be that the behaviour of the "system" installed package should **not** write a log to a user specific location

**Comment by BenjaminRS** [comment]
even if it is under /tmp/ ?

**Comment by bdorney** [comment]
> My only constraint here would be that the behaviour of the "system" installed package should **not** write a log to a user specific location

@jsturdy is it possible for the logger to set the permissions on the log file to have group write permissions?  This would then probably resolve the issue at hand?
